name: Pipeline

on: 
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.17

    - name: Set up Codecov
      uses: codecov/codecov-action@v4

    - name: Run tests
      run: |
        go test ./tests/... -cover \
          -coverpkg=./controllers,./helpers \
          -coverprofile=coverage.out

    - name: Upload coverage report
      run: bash <(curl -s http://codecov.io/bash)
